/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fashionshop;


import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author thara
 */
public class PlaceOrderForm extends javax.swing.JFrame {
     //private OrderList orderList;
     //private int orderStatus = Demo.PROCESSING;
    /**
     * Creates new form PlaceOrderForm
     */
    private int orderStatus = MainForm.PROCESSING;
    public PlaceOrderForm() {
        
        initComponents();
        setResizable(false);  
        setLocationRelativeTo(null);
        OrderIdGenerateLabel.setText(OrderController.generateId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OrderIdGenerateLabel = new javax.swing.JLabel();
        CustomerIdTextField = new javax.swing.JTextField();
        SizeComboBox = new javax.swing.JComboBox<>();
        QtyTextField = new javax.swing.JTextField();
        AmountLabel = new javax.swing.JLabel();
        PlaceOrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BackButton.setBackground(new java.awt.Color(255, 60, 60));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Order Id :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Customer Id :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Size :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("QTY : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Amount : ");

        OrderIdGenerateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OrderIdGenerateLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                OrderIdGenerateLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        CustomerIdTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CustomerIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIdTextFieldActionPerformed(evt);
            }
        });

        SizeComboBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        SizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeComboBoxActionPerformed(evt);
            }
        });

        QtyTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        QtyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyTextFieldActionPerformed(evt);
            }
        });

        AmountLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        PlaceOrderButton.setBackground(new java.awt.Color(10, 255, 40));
        PlaceOrderButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PlaceOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        PlaceOrderButton.setText("Place");
        PlaceOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerIdTextField)
                    .addComponent(OrderIdGenerateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SizeComboBox, 0, 248, Short.MAX_VALUE)
                    .addComponent(QtyTextField)
                    .addComponent(AmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PlaceOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderIdGenerateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QtyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(PlaceOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        QtyTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                calculateAmount();
            }

            public void removeUpdate(DocumentEvent e) {
                calculateAmount();
            }

            public void insertUpdate(DocumentEvent e) {
                calculateAmount();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         MainForm mainform = new MainForm();       
         mainform.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CustomerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerIdTextFieldActionPerformed

    private void SizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeComboBoxActionPerformed
        // TODO add your handling code here:
        calculateAmount();
    }//GEN-LAST:event_SizeComboBoxActionPerformed
            
    private void PlaceOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderButtonActionPerformed
        //String id=OrderIdGenerateLabel.getText();
        String customerId=CustomerIdTextField.getText();
        String selectedSize = (String) SizeComboBox.getSelectedItem();
        String qtyText = QtyTextField.getText();
        
        if (!OrderUtils.validPhoneNumber(customerId)) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID. Please enter a valid 10-digit phone number starting with 0.");
        } else if (!OrderUtils.validSize(selectedSize)) {
            JOptionPane.showMessageDialog(null, "Invalid Size. Please select a valid size.");
        } else if (qtyText.isEmpty() || !OrderUtils.validQuantity(Integer.parseInt(qtyText))) {
            JOptionPane.showMessageDialog(null, "Invalid Quantity. Please enter a valid quantity.");
        } else {
            int qty = Integer.parseInt(qtyText);
            double amount = OrderUtils.getAmountBySize(selectedSize) * qty;
            AmountLabel.setText(String.format("%.2f", amount));
            
            orderStatus = MainForm.PROCESSING;
            
            Order order = new Order(OrderController.generateId(), customerId, selectedSize, qty, orderStatus);
            OrderController.addOrder(order);
            JOptionPane.showMessageDialog(null, "Order placed successfully!");
            
            CustomerIdTextField.setText("");
            QtyTextField.setText("");
            SizeComboBox.setSelectedIndex(0);

           
            OrderIdGenerateLabel.setText(OrderController.generateId());
        }
        
    }//GEN-LAST:event_PlaceOrderButtonActionPerformed
    private void calculateAmount() {
    String selectedSize = (String) SizeComboBox.getSelectedItem();
    //System.out.println("Selected Size: " + selectedSize); 
    String qtyText = QtyTextField.getText();

    if (!OrderUtils.validSize(selectedSize) || qtyText.isEmpty() || !OrderUtils.validQuantity(Integer.parseInt(qtyText))) {
        AmountLabel.setText(""); 
    } else {
        int qty = Integer.parseInt(qtyText);
        double amount = OrderUtils.getAmountBySize(selectedSize) * qty;
        AmountLabel.setText(String.format("%.2f", amount));
    }
}
    private void OrderIdGenerateLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_OrderIdGenerateLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderIdGenerateLabelAncestorAdded
    
    private void QtyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyTextFieldActionPerformed
       
    }//GEN-LAST:event_QtyTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CustomerIdTextField;
    private javax.swing.JLabel OrderIdGenerateLabel;
    private javax.swing.JButton PlaceOrderButton;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JComboBox<String> SizeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
